version: '2'

services:
  ca.vlf.zx.rs:
    image: hyperledger/fabric-ca:$ARCH-1.0.6
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.vlf.zx.rs

    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.vlf.zx.rs-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/ba4344868caf22aac415ea4bbb9fa293cbb3b68c49c61728ee7fda1d6173113c_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/vlf.zx.rs/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.vlf.zx.rs

  orderer.vlf.zx.rs:
    container_name: orderer.vlf.zx.rs
    image: hyperledger/fabric-orderer:$ARCH-1.0.6
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/composer-genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/vlf.zx.rs/orderers/orderer.vlf.zx.rs/msp:/etc/hyperledger/msp/orderer/msp

  peer0.vlf.zx.rs:
    container_name: peer0.vlf.zx.rs
    image: hyperledger/fabric-peer:$ARCH-1.0.6
    environment:
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.vlf.zx.rs
      - CORE_PEER_ADDRESS=peer0.vlf.zx.rs:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=composer_default
      - CORE_PEER_LOCALMSPID=VLFMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start --peer-defaultchain=false
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/vlf.zx.rs/peers/peer0.vlf.zx.rs/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/vlf.zx.rs/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.vlf.zx.rs
      - couchdb

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb:$ARCH-1.0.6
    ports:
      - 5984:5984
    environment:
      DB_URL: http://localhost:5984/member_db


  peer1.vlf.zx.rs:
    container_name: peer1.vlf.zx.rs
    image: hyperledger/fabric-peer:$ARCH-1.0.6
    environment:
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.vlf.zx.rs
      - CORE_PEER_ADDRESS=peer1.vlf.zx.rs:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=composer_default
      - CORE_PEER_LOCALMSPID=VLFMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start --peer-defaultchain=false
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/vlf.zx.rs/peers/peer1.vlf.zx.rs/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/vlf.zx.rs/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.vlf.zx.rs
      - couchdb1

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb:$ARCH-1.0.6
    ports:
      - 6984:5984
    environment:
      DB_URL: http://localhost:6984/member_db


